"use client";

import { useState, useEffect } from 'react';

export interface User {
  fullName: string;
  email: string;
  userId: number;
}

export function useUser() {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadUser = () => {
      const storedUser = localStorage.getItem('user');
      if (storedUser) {
        try {
          setUser(JSON.parse(storedUser));
        } catch (e) {
          console.error("Failed to parse user data", e);
        }
      }
      setLoading(false);
    };

    loadUser();

    // Listen for storage events (generated by updates in other tabs or manually dispatched)
    window.addEventListener('storage', loadUser);
    
    return () => {
      window.removeEventListener('storage', loadUser);
    };
  }, []);

  return { user, loading };
}
